server:
  port: 8765
spring:
  application:
    name: swagger-test
# swagger-ui custom path
springdoc:
#  swagger-ui:
#    path : /swagger-ui.html #默认swaggerUI路径，可通过配置更改
  packages-to-scan: 
    - com.test #指定哪些包下的接口被扫描，如果不指定会将引入的所有接口扫描，包括依赖包如base包中的共通接口
  group-configs:
#    - group: 'test'
#      paths-to-match: '/test/**'
#      #生成文档所需的扫包路径，一般为启动类目录
#      #packages-to-scan: com.psdcd
#    - group: 'test2' 
#      paths-to-match: '/test2/**'
    - group: 'all'
      paths-to-match: '/test**/**'

#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
  basic:
    enable: true
    username: admin
    password: 123456
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
    swagger-model-name: 用户模块		
